pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
      # For some reason mergify doesn't accept ci job name
      # - check-success=Build and Test
      - title~=^Bump [^\s]+ from ([\d]+)\..+ to \1\.
    actions: 
      merge:
        method: merge